version: '3.8'

services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: discount-calculator-api
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
